config/routes.rb
Rails.application.routes.draw do
  root :to =>'admin/users#index'
  get "/admin" => "admin/users#index"

  devise_for :users, :controllers => { :sessions => "sessions",:registrations => "registrations",:passwords => "passwords",:confirmations => "confirmations" }

  namespace :admin do

    resources :users do
      collection do
        get "/user_password/:id" => "users#passukkkkword"
        post "/more_user" => "users#more_user"
        post "/change_password/:id" => "users#change_password"
      end
    end

    resources :sum_messages do 
      collection do
        post "/more_sum_message" => "sum_messages#more_sum_message"
      end
    end

    resources :documents do
      collection do
        post "/more_document" => "documents#more_document"
      end
    end

  end

  # 通过 /resque 可以访问后台的管理页面
  mount Resque::Server, :at => "/resque"

  # api
  namespace :api do
    namespace :v1 do
      resources :sum_messages do
        collection do
          get "read_file"
        end
      end
    end
  end
  
end

app/models/sum_message.rb
class SumMessage < ActiveRecord::Base

	def show_genre
    {1 => "type1", 2 => "type2", 3 => "type3"}[self.genre]
  end
  class << self
	  # parse date
	  def parse_mark_date(type, date_mark)
	  	if type == "day"
	      if date_mark.blank?
	        # 默认当天day
	        date_mark = Time.now.to_s[0, 8]
	      else
	        # 截取成day 如下：
	        # "2016/04/13 - 10" => 20160413
	        date_mark[0,10].gsub(/\//, '')
	      end
	    else
	      if date_mark.blank?
	        # 默认当天day
	        date_mark = Time.now.to_s
	      else
	        # 截取成hour 如下:
	        # "2016/04/13 - 10" => 2016041310
	        date_mark.gsub(/\//, '').gsub(/ /, '').gsub(/-/, '')
	      end
	    end
	  end

	  # before month
	  def parse_before_month
	  	# 以time_line为坐标轴吐前一个月的数据
	    time_line = Time.now.to_s
	    if time_line[4,1].to_i.zero?
	    	before_date = time_line.gsub(time_line[5, 1], "#{ time_line[5,1].to_i - 1 }")
	    elsif time_line[5, 1].to_i.zero?
	    	before_date = time_line.gsub(time_line[4, 2], "#{ "0"+(before_date[4,2].to_i - 1).to_s }")
	    else
	    	before_date = time_line.gsub(time_line[4, 2], "#{ time_line[4,2].to_i - 1 }")
	    end
	  end

	  # 数据分析（吐给前端上一个月的数据格式／不满一个月吐出所有数据）
	  def analyze_before_month_dates(post_id)
	  	HourMessage.where("post_id = #{post_id} and hour_mark < #{parse_before_month}")
	  end

	end

end

app/controllers/admin/sum_messages_controller.rb
# coding: utf-8
class Admin::SumMessagesController < Admin::BaseController

  def index
  end

  def more_sum_message
    @search = params[:search][:value] ? params[:search][:value] : ""
    @per_page = params[:per_page] ? params[:per_page] : 10
    page = params[:page] || 1
    start = params[:start].to_i || 0
    length = params[:length] ? params[:length].to_i : 10
    page = (start / length) + 1
    @per_page = length
    if params[:optionsRadios].blank? && params[:dateMark].blank?
      # 默认sum_messages
      sum_messages = SumMessage.where(["post_id like ?", "%%#{@search}%%"]).paginate(page: page , per_page: @per_page).order("id DESC")
      data = sum_messages.collect { |item| {:id => item.id, :post_id => item.post_id, :impression_count => item.impression_count, :click_count => item.click_count, :comment_count => item.comment_count, :praise_count => item.praise_count, :qq_share => item.qq_share, :wechat_share => item.wechat_share, :weibo_share => item.weibo_share, :genre => item.show_genre} }
      has_more = (sum_messages.length == 0 ? false : true)
      all_count = sum_messages.count
    else
      # day_message or hour_messages
      date_mark = SumMessage.parse_mark_date(params[:optionsRadios], params[:dateMark])
      messages = date_messsage(params[:optionsRadios], date_mark)
      messages = messages.where(["post_id like ?", "%%#{@search}%%"]).paginate(page: page , per_page: @per_page).order("id DESC")
      data = messages.collect { |item| {:id => item.id, :post_id => item.post_id, :impression_count => item.impression_count, :click_count => item.click_count, :comment_count => item.comment_count, :praise_count => item.praise_count, :qq_share => item.qq_share, :wechat_share => item.wechat_share, :weibo_share => item.weibo_share, :genre => item.show_genre} }
      has_more = (messages.length == 0 ? false : true)
      all_count = messages.count
    end
    draw = params[:draw].to_i + 1
    render :json => {:draw => draw, :has_more => has_more, :start => start, :recordsTotal => all_count, :recordsFiltered => all_count, :data => data }
  end

  def show
    SumMessage.analyze_before_month_dates(params[:id])
  end

  private

  def date_messsage(type, date_mark)
    if type == "day"
      DayMessage.fetch_datas(date_mark)
    else
      HourMessage.fetch_datas(date_mark)
    end
  end

  def sum_message_params
    params.require(:sum_message).permit(:post_id, :impression_count, :click_count, :comment_count, :praise_count, :qq_share, :wechat_share, :weibo_share, :genre)
  end
end

app/controllers/api/v1/sum_messages_controller.rb
class Api::V1::SumMessagesController < Admin::BaseController
	
	def read_file
		result = true
		msg = "successly"
		# 上传操作
		scheduler = Rufus::Scheduler.new
		scheduler.every  '10s'  do
			async_create_message
		end
		# render json: {status: result, msg: msg}
	end

	private

	# 异步任务（定时去跑异步任务晚上计算） rake resque:work QUEUE='*' 
	def async_create_message
		Resque.enqueue(HourMessageWorker)
		Resque.enqueue(DayMessageWorker)
		Resque.enqueue(SumMessageWorker)
	end

end

app/views/admin/sum_messages/index.html.erb
<!-- BEGIN PAGE HEAD -->
<div class="page-head">
  <div class="container">
    <!-- BEGIN PAGE TITLE -->
    <div class="page-title">
      <h1>数据统计</h1>
    </div>
    <!-- END PAGE TITLE -->
  </div>
</div>
<!-- END PAGE HEAD -->
<!-- BEGIN PAGE CONTENT -->
<div class="page-content">
  <div class="container">
    <!-- BEGIN PAGE BREADCRUMB -->
    <ul class="page-breadcrumb breadcrumb">
      <li class="active">统计列表页</li>
    </ul>
    <!-- END PAGE BREADCRUMB -->

    <!-- BEGIN PAGE CONTENT INNER -->
      <div class="row">
        <div class="col-md-12">
          <!-- Begin: life time stats -->
          <div class="portlet light">
            <div class="portlet-title">
              <div class="caption">
                <i class="fa fa-gift font-green-sharp"></i>
                <span class="caption-subject font-green-sharp bold uppercase">统计列表</span>
                <span class="caption-helper">管理统计</span>
              </div>
              <div class="actions">
                  <form class="filter-form" action="/">
                      <input type="text" size="16" id="date_mark" name="dateMark" readonly class="form-control form_datetime">

                      <label class="radio-inline">
                        <input type="radio" id="day" name="optionsRadios" value="day" checked> 天级
                      </label>
                      <label class="radio-inline">
                        <input type="radio" id="hour" name="optionsRadios" value="hour"> 小时级
                      </label>

                      <a href="#" class="btn btn-default submit">查询</a>
                  </form>
              </div>
            </div>

            <div class="portlet-body">
              <div class="table-container">
                <table class="com-datatable-ajax table table-striped table-bordered table-hover" data-url="<%= more_sum_message_admin_sum_messages_path %>">
                  <thead>
                    <tr role="row" class="heading">
                        <th class="table-checkbox" width="6%">
                          <input type="checkbox" class="group-checkable" />
                        </th>
                        <th>文章ID</th>
                        <th>浏览量</th>
                        <th>点击量</th>
                        <th>评论量</th>
                        <th>赞数</th>
                        <th>QQ分享</th>
                        <th>微信分享</th>
                        <th>微博分享</th>
                        <th>文章类型</th>
                        <th width="12%">操作</th>
                    </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <!-- End: life time stats -->
        </div>
      </div>
      <!-- END PAGE CONTENT INNER -->
  </div>
</div>
<!-- END PAGE CONTENT -->

app/views/admin/sum_messages/show.html.erb
报表显示