config/routes.rb
Rails.application.routes.draw do
  root :to =>'admin/users#index'
  get "/admin" => "admin/users#index"

  devise_for :users, :controllers => { :sessions => "sessions",:registrations => "registrations",:passwords => "passwords",:confirmations => "confirmations" }

  namespace :admin do

    resources :users do
      collection do
        get "/user_password/:id" => "users#passukkkkword"
        post "/more_user" => "users#more_user"
        post "/change_password/:id" => "users#change_password"
      end
    end

    resources :sum_messages do 
      collection do
        post "/more_sum_message" => "sum_messages#more_sum_message"
      end
    end

    resources :documents do
      collection do
        post "/more_document" => "documents#more_document"
      end
    end

  end

  # 通过 /resque 可以访问后台的管理页面
  mount Resque::Server, :at => "/resque"

  # api
  namespace :api do
    namespace :v1 do
      resources :sum_messages do
        collection do
          get "read_file"
        end
      end
    end
  end
  
end

app/models/document.rb
class Document < ActiveRecord::Base

	def show_file_state
    {0 => "未读", 1 => "已读"}[self.file_state]
  end

  # 生成一层文件夹
  Paperclip.interpolates :day do |attachment, style|
    attachment.instance.created_at.strftime("%Y%m%d")
  end

  # 生成两层文件夹
  Paperclip.interpolates :hour do |attachment, style|
    attachment.instance.created_at.strftime("%Y%m%d%H")[attachment.instance.created_at.strftime("%Y%m%d%H").length-2,2]
  end

  has_attached_file :file, 
	:url => "/:attachment/:day/:hour/:basename.:extension", # 文件访问路径
	:path => ":rails_root/public/:attachment/:day/:hour/:basename.:extension" # 文件存放路径 :rails_root 给用户设置存放的root权限
	#validates_attachment_size :avatar, :less_than => 2.megabytes # 文件大小限制
  validates_attachment_content_type :file, content_type: ["text/csv"]

  class << self

    def final_document
      Document.last.file_state.zero? ? true : false
    end

    def read_file_dates
      require 'csv'
      document = Document.last
      if final_document
        document.update(file_state: 1)
        day = document.file_updated_at.to_s[0, 8]
        hour = document.file_updated_at.to_s[8, 2]
        filename = document.file_file_name
        hour_dates = CSV.open "public/files/#{day}/#{hour}/#{filename}"
        hour_dates.read
      end
    end

  end

end

app/controllers/admin/documents_controller.rb
# coding: utf-8
class Admin::DocumentsController < Admin::BaseController

  def index
  end

  def more_document
    @search = params[:search][:value] ? params[:search][:value] : ""
    @per_page = params[:per_page] ? params[:per_page] : 10
    page = params[:page] || 1
    start = params[:start].to_i || 0
    length = params[:length] ? params[:length].to_i : 10
    page = (start / length) + 1;
    @per_page = length;
    documents = Document.where(["file_file_name like ?", "%%#{@search}%%"]).paginate(page: page , per_page: @per_page).order("id DESC")
    data = documents.collect { |item| {:id => item.id, :file_file_name => item.file_file_name, :file_content_type => item.file_content_type, :file_file_size => item.file_file_size,  :file_updated_at => item.file_updated_at.to_date, :file_state => item.show_file_state } }
    has_more = (documents.length == 0 ? false : true)
    all_count = documents.count
    draw = params[:draw].to_i + 1
    render :json => {:draw => draw, :has_more => has_more, :start => start, :recordsTotal => all_count, :recordsFiltered => all_count, :data => data }
  end

  def new
    @document = Document.new
  end

  def create
    sum = Api::V1::SumMessagesController.new
    @document = Document.new(document_params)
    if @document.save
      sum.read_file
      redirect_to admin_documents_url, notice: '新建成功！'
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to admin_documents_url
  end

  private

  def document_params
    params.require(:document).permit(:file)
  end
end

app/views/admin/documents/_form.html.erb
<!-- BEGIN VALIDATION STATES-->
<div class="portlet light">
  <div class="portlet-title">
    <div class="caption">
      <i class="fa fa-cogs font-green-sharp"></i>
      <span class="caption-subject font-green-sharp bold uppercase">上传文件</span>
    </div>
  </div>
  <div class="portlet-body form">
    <!-- BEGIN FORM-->
    <%= form_for([:admin, @document], :html => {:class => 'form-horizontal clearfix user-form-validate', :role => 'form'}) do |f| %>
    <div class="form-body">      
      <%= f.file_field :file %>
    </div>
    <div class="form-actions">
        <div class="row">
            <div class="col-md-offset-3 col-md-9">
                <%= link_to '返回', admin_users_path, :class => 'btn btn-default' %>
                <% if action_name == 'new' %>
                <button type="submit" class="btn green">保存</button>
                <% else %>
                <button type="submit" class="btn green">更新</button>
                <% end %>
            </div>
        </div>
    </div>
    <% end %>
    <!-- END FORM-->
  </div>
</div>
<!-- END VALIDATION STATES-->

app/views/admin/documents/index.html.erb
<!-- BEGIN PAGE HEAD -->
<div class="page-head">
  <div class="container">
    <!-- BEGIN PAGE TITLE -->
    <div class="page-title">
      <h1>文件路径管理</h1>
    </div>
    <!-- END PAGE TITLE -->
  </div>
</div>
<!-- END PAGE HEAD -->
<!-- BEGIN PAGE CONTENT -->
<div class="page-content">
  <div class="container">
    <!-- BEGIN PAGE BREADCRUMB -->
    <ul class="page-breadcrumb breadcrumb">
      <li class="active">文件url列表</li>
    </ul>
    <!-- END PAGE BREADCRUMB -->

    <!-- BEGIN PAGE CONTENT INNER -->
      <div class="row">
        <div class="col-md-12">
          <!-- Begin: life time stats -->
          <div class="portlet light">
            <div class="portlet-title">
              <div class="caption">
                <i class="fa fa-gift font-green-sharp"></i>
                <span class="caption-subject font-green-sharp bold uppercase">文件URL列表</span>
                <span class="caption-helper">管理URL</span>
              </div>
              <div class="actions">
                <a href="<%= new_admin_document_path %>" class="btn btn-default btn-circle">
                  <i class="fa fa-plus"></i>
                  <span class="hidden-480">上传测试文件</span>
                </a>
              </div>
            </div>
            <div class="portlet-body">
              <div class="table-container">
                <table class="com-datatable-ajax table table-striped table-bordered table-hover" data-url="<%= more_document_admin_documents_path %>">
                  <thead>
                    <tr role="row" class="heading">
                      <th class="table-checkbox" width="6%">
                        <input type="checkbox" class="group-checkable" />
                      </th>
                      <th>文件名称</th>
                      <th>文件内容类型</th>
                      <th>文件大小</th>
                      <th>文件更新日期</th>
                      <th>是否已读</th>
                      <th width="12%">操作</th>
                    </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <!-- End: life time stats -->
        </div>
      </div>
      <!-- END PAGE CONTENT INNER -->
  </div>
</div>
<!-- END PAGE CONTENT

app/views/admin/documents/new.html.erb
<!-- BEGIN PAGE CONTENT -->
<div class="page-content">
    <div class="container">
        <%= render :partial => 'components/admin/page-breadcrumb/index' %>

        <!-- BEGIN PAGE CONTENT INNER -->
        <div class="row">
            <div class="col-md-12">
                <!-- Begin: life time stats -->
                <%= render :partial => 'form' %>
                <!-- End: life time stats -->
            </div>
        </div>
        <!-- END PAGE CONTENT INNER -->
    </div>
</div>
<!-- END PAGE CONTENT -->