config/routes.rb
Rails.application.routes.draw do
  root :to =>'admin/users#index'
  get "/admin" => "admin/users#index"

  devise_for :users, :controllers => { :sessions => "sessions",:registrations => "registrations",:passwords => "passwords",:confirmations => "confirmations" }

  namespace :admin do

    resources :users do
      collection do
        get "/user_password/:id" => "users#passukkkkword"
        post "/more_user" => "users#more_user"
        post "/change_password/:id" => "users#change_password"
      end
    end

    resources :sum_messages do 
      collection do
        post "/more_sum_message" => "sum_messages#more_sum_message"
      end
    end

    resources :documents do
      collection do
        post "/more_document" => "documents#more_document"
      end
    end

  end

  # 通过 /resque 可以访问后台的管理页面
  mount Resque::Server, :at => "/resque"

  # api
  namespace :api do
    namespace :v1 do
      resources :sum_messages do
        collection do
          get "read_file"
        end
      end
    end
  end
  
end

app/models/user.rb
# coding: utf-8
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :face,
  :styles => { :medium => "180x180#",
    :small => "80x80#",
    },
    :default_url => "/img/missing_face.png",
    :url => "/system/:class/:attachment/:id/:style/:id.:extension",
    :whiny => false

  has_many :posts

  def show_genre
    {1 => "主编", 2 => "值班编辑", 3 => "记者", 4 => "普通用户", 5 => "市场"}[self.genre]
  end

  def self.get_all_author
    # TODO: cache all_author
    Rails.cache.fetch("all_author/#{User.count}", expires_in: 10*60.seconds) do
      authors = User.where({:genre => [1, 2, 3]})
    end
  end

end

app/controllers/admin/users_controller.rb
# coding: utf-8
class Admin::UsersController < Admin::BaseController

  before_action :find_user, only: [:edit, :update, :password, :change_password, :destroy]

  def index
  end

  def more_user
    @search = params[:search][:value] ? params[:search][:value] : ""
    @per_page = params[:per_page] ? params[:per_page] : 10
    page = params[:page] || 1
    start = params[:start].to_i || 0
    length = params[:length] ? params[:length].to_i : 10
    page = (start / length) + 1;
    @per_page = length;
    users = User.where(["username like ? and state = ?", "%%#{@search}%%", true]).paginate(page: page , per_page: @per_page).order("id DESC")
    data = users.collect { |item| {:id => item.id, :username => item.username, :email => item.email, :phone => item.phone, :genre => item.show_genre} }
    has_more = (users.length == 0 ? false : true)
    all_count = users.count
    draw = params[:draw].to_i + 1
    render :json => {:draw => draw, :has_more => has_more, :start => start, :recordsTotal => all_count, :recordsFiltered => all_count, :data => data }
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_url, notice: '新建成功！'
    else
      render :new
    end
  end

  def update
    get_user_params = user_params
    get_user_params.except!(:password, :password_confirmation) if user_params[:password].blank? && user_params[:password_confirmation].blank?
    if @user.update(get_user_params)
      redirect_to admin_users_url, notice: '更新成功！'
    else
      render :edit
    end
  end

  def password
    render json: @user
  end

  def change_password
    if @user.update(user_params)
      redirect_to "/admin/users"
    else
      redirect_to "/admin/users"
    end
  end

  def destroy
    @user.state? ? @user.update(state: false) : @user.update(state: true)
    redirect_to admin_users_url
  end

  private

  def find_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :remember_me, :username, :user_pic , :genre, :description, :phone, :phone_verify, :private_token, :weibo_uid, :qq_uid, :wechat_uid, :twitter_uid, :message_count ,:background_image_pic , :source , :_alias , :comments_push_switch , :praises_push_switch , :letter_push_switch , :letter_count, :address, :status)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<!-- BEGIN VALIDATION STATES-->
<div class="portlet light">
  <div class="portlet-title">
    <div class="caption">
      <i class="fa fa-cogs font-green-sharp"></i>
      <span class="caption-subject font-green-sharp bold uppercase">新建用户</span>
    </div>
  </div>
  <div class="portlet-body form">
    <!-- BEGIN FORM-->
    <%= form_for([:admin, @user], :html => {:class => 'form-horizontal clearfix user-form-validate', :role => 'form'}) do |f| %>
    <div class="form-body">

      <div class="form-group">
        <%= f.label(:username, :class => "control-label col-md-3") do %>
        用户名<span class="required">*</span>
        <% end %>
        <div class="col-md-4">
          <%= f.text_field(:username, :placeholder => '用户名', :class => 'form-control') %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label(:email, :class => "control-label col-md-3") do %>
        邮箱<span class="required">*</span>
        <% end %>
        <div class="col-md-4">
          <%= f.text_field(:email, :placeholder => '邮箱', :class => 'form-control') %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label(:phone, :class => "control-label col-md-3") do %>
        手机号
        <% end %>
        <div class="col-md-4">
          <%= f.text_field(:phone, :placeholder => '手机号', :class => 'form-control') %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label(:genre,  '用户类型', :class => "col-md-3 control-label") %>
        <div class="col-md-4">
          <%= f.select(:genre, [['主编', 1],['值班编辑', 2],['记者', 3],['普通用户', 4],['市场', 5]], {}, :class => 'form-control') %>
        </div>
      </div>           

      <div class="form-group fileupload">
        <%= f.label(:face_pic, "头像", :class => "col-md-3 control-label") %>
        <div class="col-md-4">
          <div class="fileinput small fileinput-new" data-provides="fileinput">
            <div class="fileinput-new thumbnail">
              <img src="<%= @user.face_pic %>" alt=""/>
            </div>
            <div class="fileinput-preview fileinput-exists thumbnail"></div>
            <div>
              <span class="btn btn-default btn-file">
                <span class="fileinput-new">选择(180*180)</span>
                <span class="fileinput-exists">替换</span>
                <%= f.file_field(:face_pic, :accept => "image/*") %>
              </span>
              <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">移除</a>
            </div>
          </div>
        </div>
      </div>

      <div class="form-group fileupload">
        <%= f.label(:background_image_pic, "背景图", :class => "col-md-3 control-label") %>
        <div class="col-md-4">
          <div class="fileinput small fileinput-new" data-provides="fileinput">
            <div class="fileinput-new thumbnail">
              <img src="<%= @user.background_image_pic %>" alt=""/>
            </div>
            <div class="fileinput-preview fileinput-exists thumbnail"></div>
            <div>
              <span class="btn btn-default btn-file">
                <span class="fileinput-new">选择(500*200)</span>
                <span class="fileinput-exists">替换</span>
                <%= f.file_field(:background_image_pic, :accept => "image/*") %>
              </span>
              <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">移除</a>
            </div>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label(:password, :class => "control-label col-md-3") do %>
        密码
        <% end %>
        <div class="col-md-4">
          <%= f.text_field(:password, :placeholder => '密码', :class => 'form-control') %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label(:password_confirmation, :class => "control-label col-md-3") do %>
        确认密码
        <% end %>
        <div class="col-md-4">
          <%= f.text_field(:password_confirmation, :placeholder => '确认密码', :class => 'form-control') %>
        </div>
      </div>      


    </div>
    <div class="form-actions">
        <div class="row">
            <div class="col-md-offset-3 col-md-9">
                <%= link_to '返回', admin_users_path, :class => 'btn btn-default' %>
                <% if action_name == 'new' %>
                <button type="submit" class="btn green">保存</button>
                <% else %>
                <button type="submit" class="btn green">更新</button>
                <% end %>
            </div>
        </div>
    </div>
    <% end %>
    <!-- END FORM-->
  </div>
</div>
<!-- END VALIDATION STATES-->

app/views/admin/users/edit.html.erb
<!-- BEGIN PAGE CONTENT -->
<div class="page-content">
    <div class="container">
        <%= render :partial => 'components/admin/page-breadcrumb/index' %>

        <!-- BEGIN PAGE CONTENT INNER -->
        <div class="row">
            <div class="col-md-12">
                <!-- Begin: life time stats -->
                <%= render :partial => 'form' %>
                <!-- End: life time stats -->
            </div>
        </div>
        <!-- END PAGE CONTENT INNER -->
    </div>
</div>
<!-- END PAGE CONTENT -->

app/views/admin/users/index.html.erb
<!-- BEGIN PAGE HEAD -->
<div class="page-head">
  <div class="container">
    <!-- BEGIN PAGE TITLE -->
    <div class="page-title">
      <h1>用户列表</h1>
    </div>
    <!-- END PAGE TITLE -->
  </div>
</div>
<!-- END PAGE HEAD -->
<!-- BEGIN PAGE CONTENT -->
<div class="page-content">
  <div class="container">
    <!-- BEGIN PAGE BREADCRUMB -->
    <ul class="page-breadcrumb breadcrumb">
      <li class="active">用户列表页</li>
    </ul>
    <!-- END PAGE BREADCRUMB -->

    <!-- BEGIN PAGE CONTENT INNER -->
      <div class="row">
        <div class="col-md-12">
          <!-- Begin: life time stats -->
          <div class="portlet light">
            <div class="portlet-title">
              <div class="caption">
                <i class="fa fa-gift font-green-sharp"></i>
                <span class="caption-subject font-green-sharp bold uppercase">用户列表</span>
                <span class="caption-helper">管理用户</span>
              </div>
              <div class="actions">
                <a href="<%= new_admin_user_path %>" class="btn btn-default btn-circle">
                  <i class="fa fa-plus"></i>
                  <span class="hidden-480"> 新建用户</span>
                </a>
              </div>
            </div>
            <div class="portlet-body">
              <div class="table-container">
                <table class="com-datatable-ajax table table-striped table-bordered table-hover" data-url="<%= more_user_admin_users_path %>">
                  <thead>
                    <tr role="row" class="heading">
                        <th class="table-checkbox" width="6%">
                            <input type="checkbox" class="group-checkable" />
                        </th>
                        <th>用户名</th>
                        <th>邮箱</th>
                        <th>手机号</th>
                        <th>用户类型</th>
                        <th width="12%">操作</th>
                    </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <!-- End: life time stats -->
        </div>
      </div>
      <!-- END PAGE CONTENT INNER -->
  </div>
</div>
<!-- END PAGE CONTENT -->

app/views/admin/users/new.html.erb
<!-- BEGIN PAGE CONTENT -->
<div class="page-content">
    <div class="container">
        <%= render :partial => 'components/admin/page-breadcrumb/index' %>

        <!-- BEGIN PAGE CONTENT INNER -->
        <div class="row">
            <div class="col-md-12">
                <!-- Begin: life time stats -->
                <%= render :partial => 'form' %>
                <!-- End: life time stats -->
            </div>
        </div>
        <!-- END PAGE CONTENT INNER -->
    </div>
</div>
<!-- END PAGE CONTENT -->