config/routes.rb
Rails.application.routes.draw do
  root :to =>'admin/users#index'
  get "/admin" => "admin/users#index"

  devise_for :users, :controllers => { :sessions => "sessions",:registrations => "registrations",:passwords => "passwords",:confirmations => "confirmations" }

  namespace :admin do

    resources :users do
      collection do
        get "/user_password/:id" => "users#passukkkkword"
        post "/more_user" => "users#more_user"
        post "/change_password/:id" => "users#change_password"
      end
    end

    resources :sum_messages do 
      collection do
        post "/more_sum_message" => "sum_messages#more_sum_message"
      end
    end

    resources :documents do
      collection do
        post "/more_document" => "documents#more_document"
      end
    end

  end

  # 通过 /resque 可以访问后台的管理页面
  mount Resque::Server, :at => "/resque"

  # api
  namespace :api do
    namespace :v1 do
      resources :sum_messages do
        collection do
          get "read_file"
        end
      end
    end
  end
  
end

app/views/layouts/_header.html.erb
<!-- BEGIN HEADER -->
<div class="page-header">
    <!-- BEGIN HEADER TOP -->
    <div class="page-header-top">
        <div class="container">
            <!-- BEGIN LOGO -->
            <div class="page-logo">
                <a href="/admin">
                    <img src="/img/admin/logo.png" alt="logo" class="logo-default">
                </a>
            </div>
            <!-- END LOGO -->
            <!-- BEGIN RESPONSIVE MENU TOGGLER -->
            <a href="javascript:;" class="menu-toggler"></a>
            <!-- END RESPONSIVE MENU TOGGLER -->
            <!-- BEGIN TOP NAVIGATION MENU -->
            <div class="top-menu">
                <ul class="nav navbar-nav pull-right">
                  <% if current_user %>
                    <li class="dropdown dropdown-user dropdown-dark">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <img alt="" class="img-circle" src="<%= current_user.face(:small) %>">
                        <span class="username username-hide-mobile"><%= current_user.email %></span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-default">
                            <li>
                                <a href="<%= edit_admin_user_path current_user %>">
                                <i class="icon-user"></i> 个人信息 </a>
                            </li>
                            <li>
                                <a href="<%= destroy_user_session_path %>" data-method="delete">
                                <i class="icon-key"></i> 退出登录 </a>
                            </li>
                        </ul>
                    </li>
                  <% end %>
                    <!-- END USER LOGIN DROPDOWN -->
                </ul>
            </div>
            <!-- END TOP NAVIGATION MENU -->
        </div>
    </div>
    <!-- END HEADER TOP -->
    <!-- BEGIN HEADER MENU -->
    <div class="page-header-menu">
        <div class="container">
            <!-- BEGIN HEADER SEARCH BOX -->
            <form class="search-form" action="extra_search.html" method="GET">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search" name="query">
                    <span class="input-group-btn">
                    <a href="javascript:;" class="btn submit"><i class="icon-magnifier"></i></a>
                    </span>
                </div>
            </form>
            <!-- END HEADER SEARCH BOX -->
            <!-- BEGIN MEGA MENU -->
            <!-- DOC: Apply "hor-menu-light" class after the "hor-menu" class below to have a horizontal menu with white background -->
            <!-- DOC: Remove data-hover="dropdown" and data-close-others="true" attributes below to disable the dropdown opening on mouse hover -->
            <div class="hor-menu ">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="<%= root_path %>">QdailyAnalytics</a>
                    </li>
                    <li class="<%= controller_name == 'sum_messages' ? 'active' : '' %>">
                        <a href="<%= admin_sum_messages_path %>">数据统计</a>
                    </li>
                    <li class="<%= controller_name == 'documents' ? 'active' : '' %>">
                        <a href="<%= admin_documents_path %>">文件管理</a>
                    </li>                   
                    <li class="<%= controller_name == 'users' ? 'active' : '' %>">
                        <a href="<%= admin_users_path %>">用户管理</a>
                    </li>
                </ul>
            </div>
            <!-- END MEGA MENU -->
        </div>
    </div>
    <!-- END HEADER MENU -->
</div>
<!-- END HEADER -->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>QdailyAnalytics管理平台</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">

    <%= stylesheet_link_tag  'pages/admin/' + controller_name + '/' + action_name, :media => "all" %>

    <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name%> <%= action_name %> <%= (controller_name == 'sessions' || controller_name == 'registrations') ? 'login' : '' %>">
    <% unless (controller_name == 'sessions' || controller_name == 'registrations') %>
        <%= render partial: 'layouts/header' %>
    <% end %>

    <!-- BEGIN CONTAINER -->
    <div class="page-container">
        <%= yield %>
    </div>
    <!-- END CONTAINER -->

    <%= javascript_include_tag 'pages/admin/' + controller_name + '/' + action_name %>
</body>
</html>